FROM python:3.7
RUN echo $(pwd)
ADD  . .
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install -r requirement.txt
RUN python -m spacy download en_core_web_sm
RUN python -m spacy download en
RUN python predict.py
EXPOSE 8080
CMD ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8080"]